### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by FaKeErik** [GamerGambit/cw2-fas2-weapon-attachment-vendor#2]
Hi, im very Interested in This Addon, but it doesnt work for me. On the Server, it doesnt show up.
Do i need an Extra Workshop Addon or Something?

**Comment by GamerGambit** [comment]
Hi, could you be a little more specific when you say it doesn't work? Since the vendor sells attachments, it requires that the player using it have at least 1 compatible weapon on them.

**Comment by FaKeErik** [comment]
Yes im sorry, 
I Downloaded the Addon and put it in the Addons Folder of the Server. After That i restarted the Server and Tried to find it. I looked at the Entities and pur vendor in the searchbar nur i couldnt find it. So i wenn in the Gun Dealer Job but there i couldnt find ist either. My Problem is, That i Cant find it. 

I hope

**Comment by GamerGambit** [comment]
That's odd. This issue was actually brought to my attention a few months back but I was unable to reproduce it on my end so I just assumed it was a server configuration issue. Would you mind [adding me](https://s.team/p/ftr-tgpq/gfptkmmj) on steam so I can try to diagnose the issue further on your server?

**Comment by P4sca1** [comment]
The issue is that the folder name is uppercase. This won't work on Unix systems.
To resolve the issue, you just need to rename the addons folder to be lowercase.

**Comment by GamerGambit** [comment]
Thank you both for helping me solve this issue. I'll push a fix for it shortly.

**Comment by GamerGambit** [comment]
I have renamed the repository in lower-case, hopefully this fixes it.
